# Docker build and push workflow

name: Docker

on:
  workflow_call:
    inputs:
      latest_only:
        description: 'Push only the latest tag'
        required: false
        default: false
        type: boolean
    secrets:
      DOCKER_PAT:
        required: true

env:
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # I'd rather not use the git build context: it introduces a asymmetry between local and remote builds.
      # For example, the .dockerignore file: in a remote build the .python-version file would not be ignored.
      # That would be problematic because:
      # - I'd rather use the .python-version file only for local development for now
      # (and instead use the Dockerfile PYTHON_VER arg to set the python version for docker builds).
      # - In a remote build with git build context the .python-version file
      # would NOT be ignored and the second uv sync in the Dockerfile would
      # download a specific cpython to /home/appuser/.local/share/uv/python/
      # (which is a path not copied over in the last stage).
      - name: Checkout
        uses: actions/checkout@v5

      - name: Retrieve Repository Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.DOCKER_IMAGE }}
            ${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{major}},enable=${{ !inputs.latest_only }}
            type=semver,pattern={{version}},enable=${{ !inputs.latest_only }}
            type=raw,value=latest,enable=${{ inputs.latest_only || github.ref_name == 'main' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
