# Docker build and push workflow

name: Docker

on:
  workflow_call:
    inputs:
      latest_only:
        description: 'Push only the latest tag'
        required: false
        default: false
        type: boolean

env:
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Retrieve Repository Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.DOCKER_IMAGE }}
            ${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{major}},enable=${{ !inputs.latest_only }}
            type=semver,pattern={{version}},enable=${{ !inputs.latest_only }}
            type=raw,value=latest,enable=${{ inputs.latest_only || is_default_branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      # - name: Build and push images
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     labels: ${{ steps.docker_meta.outputs.labels }}
