# Release workflow

name: Release

on:
  push:
    branches:
      - main
    tags:
      # Trigger on semver2 tags (without "v" prefix): 0.0.5, 1.2.3, etc.
      - "[0-9]+.[0-9]+.[0-9]+"
      # Also support pre-release versions: 1.0.0-alpha.1, 1.0.0-rc.2, etc.
      - "[0-9]+.[0-9]+.[0-9]+-*"
  workflow_dispatch:
    inputs:
      pypitarget:
        description: 'Target PyPI repository'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - testpypi
          - pypi
      push_docker_latest:
        description: 'Build and push Docker latest tag'
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  id-token: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  PYPITARGET: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.pypitarget) || 'pypi' }}

jobs:
  pypi-and-gh-release:
    uses: ./.github/workflows/pypi-and-gh-release.yml
    with:
      pypitarget: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pypitarget || 'pypi' }}
    # on tag push + manual with a test or prod pypi env.
    if: (github.event_name == 'push' && github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch' && github.event.inputs.pypitarget != 'none')
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      latest_only: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.push_docker_latest == 'true' }}
    secrets:
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
    # on tag push + manual with checkbox "push latest" on.
    if: (github.event_name == 'push' && github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_docker_latest == 'true')
